services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck: 
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s  
      timeout: 5s 
      retries: 5
      
  gateway:
    build: 
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    container_name: "gateway"
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env.development
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules